// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $live_invoke_middleware from "./routes/live/invoke/_middleware.tsx";
import * as $About from "./islands/About.tsx";
import * as $AddToCartButton from "./islands/AddToCartButton.tsx";
import * as $ApplyRangeFiltersJS from "./islands/ApplyRangeFiltersJS.tsx";
import * as $CartModalMobile from "./islands/CartModalMobile.tsx";
import * as $CategoryText from "./islands/CategoryText.tsx";
import * as $ChooseLensButton from "./islands/ChooseLensButton.tsx";
import * as $FaqContainer from "./islands/FaqContainer.tsx";
import * as $HeaderButton from "./islands/HeaderButton.tsx";
import * as $HeaderModals from "./islands/HeaderModals.tsx";
import * as $HeaderSearchbar from "./islands/HeaderSearchbar.tsx";
import * as $LazyIframe from "./islands/LazyIframe.tsx";
import * as $NavItem from "./islands/NavItem.tsx";
import * as $Newsletter from "./islands/Newsletter.tsx";
import * as $ProductImageZoom from "./islands/ProductImageZoom.tsx";
import * as $PromotionalBar from "./islands/PromotionalBar.tsx";
import * as $RangeFiltersJS from "./islands/RangeFiltersJS.tsx";
import * as $ReviewImagesModal from "./islands/ReviewImagesModal.tsx";
import * as $SearchControls from "./islands/SearchControls.tsx";
import * as $SelectedFilters from "./islands/SelectedFilters.tsx";
import * as $ShareButton from "./islands/ShareButton.tsx";
import * as $ShowMore from "./islands/ShowMore.tsx";
import * as $SliderJS from "./islands/SliderJS.tsx";
import * as $Stopwatch from "./islands/Stopwatch.tsx";
import * as $TabJS from "./islands/TabJS.tsx";
import * as $ToExperimentButton from "./islands/ToExperimentButton.tsx";
import * as $ValueItem from "./islands/ValueItem.tsx";
import * as $WishlistButton from "./islands/WishlistButton.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/live/invoke/_middleware.tsx": $live_invoke_middleware,
  },
  islands: {
    "./islands/About.tsx": $About,
    "./islands/AddToCartButton.tsx": $AddToCartButton,
    "./islands/ApplyRangeFiltersJS.tsx": $ApplyRangeFiltersJS,
    "./islands/CartModalMobile.tsx": $CartModalMobile,
    "./islands/CategoryText.tsx": $CategoryText,
    "./islands/ChooseLensButton.tsx": $ChooseLensButton,
    "./islands/FaqContainer.tsx": $FaqContainer,
    "./islands/HeaderButton.tsx": $HeaderButton,
    "./islands/HeaderModals.tsx": $HeaderModals,
    "./islands/HeaderSearchbar.tsx": $HeaderSearchbar,
    "./islands/LazyIframe.tsx": $LazyIframe,
    "./islands/NavItem.tsx": $NavItem,
    "./islands/Newsletter.tsx": $Newsletter,
    "./islands/ProductImageZoom.tsx": $ProductImageZoom,
    "./islands/PromotionalBar.tsx": $PromotionalBar,
    "./islands/RangeFiltersJS.tsx": $RangeFiltersJS,
    "./islands/ReviewImagesModal.tsx": $ReviewImagesModal,
    "./islands/SearchControls.tsx": $SearchControls,
    "./islands/SelectedFilters.tsx": $SelectedFilters,
    "./islands/ShareButton.tsx": $ShareButton,
    "./islands/ShowMore.tsx": $ShowMore,
    "./islands/SliderJS.tsx": $SliderJS,
    "./islands/Stopwatch.tsx": $Stopwatch,
    "./islands/TabJS.tsx": $TabJS,
    "./islands/ToExperimentButton.tsx": $ToExperimentButton,
    "./islands/ValueItem.tsx": $ValueItem,
    "./islands/WishlistButton.tsx": $WishlistButton,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
