// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/decohub.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";
import * as $$$0 from "./loaders/actions/cart/addItem.ts";
import * as $$$1 from "./loaders/actions/wishlist/addItem.ts";
import * as $$$2 from "./loaders/actions/wishlist/removeItem.ts";
import * as $$$3 from "./loaders/product/cart.ts";
import * as $$$4 from "./loaders/product/productDetails.ts";
import * as $$$5 from "./loaders/product/productList.ts";
import * as $$$6 from "./loaders/product/productListiningPage.ts";
import * as $$$7 from "./loaders/product/suggestions.ts";
import * as $$$8 from "./loaders/product/testimonials.ts"; 
import * as $$$9 from "./loaders/product/wishlist.ts";
import * as $$$10 from "./loaders/store/auth.ts";
import * as $$$11 from "./loaders/store/newsletter.ts";
import * as $$$12 from "./loaders/store/session.ts";
import * as $$$$$$0 from "./sections/Category/CategoryBanner.tsx";
import * as $$$$$$1 from "./sections/Category/CategoryText.tsx";
import * as $$$$$$2 from "./sections/Content/About.tsx";
import * as $$$$$$3 from "./sections/Content/AccordionGroup.tsx";
import * as $$$$$$4 from "./sections/Content/AntiBenefits.tsx";
import * as $$$$$$5 from "./sections/Content/AntiOptions.tsx";
import * as $$$$$$6 from "./sections/Content/BenefitList.tsx";
import * as $$$$$$7 from "./sections/Content/Benefits.tsx";
import * as $$$$$$8 from "./sections/Content/Cards.tsx";
import * as $$$$$$9 from "./sections/Content/CardsWithImage.tsx";
import * as $$$$$$10 from "./sections/Content/ContactForm.tsx";
import * as $$$$$$11 from "./sections/Content/ContactUs.tsx";
import * as $$$$$$12 from "./sections/Content/CouponList.tsx";
import * as $$$$$$13 from "./sections/Content/DeferredIframe.tsx";
import * as $$$$$$14 from "./sections/Content/Faq.tsx";
import * as $$$$$$15 from "./sections/Content/Hero.tsx";
import * as $$$$$$16 from "./sections/Content/Image.tsx";
import * as $$$$$$17 from "./sections/Content/InformationList.tsx";
import * as $$$$$$18 from "./sections/Content/Institutional.tsx";
import * as $$$$$$19 from "./sections/Content/Logos.tsx";
import * as $$$$$$20 from "./sections/Content/Presentation.tsx";
import * as $$$$$$21 from "./sections/Content/RichText.tsx";
import * as $$$$$$22 from "./sections/Content/SimpleCard.tsx";
import * as $$$$$$23 from "./sections/Content/Spacing.tsx";
import * as $$$$$$24 from "./sections/Content/Testimonials.tsx";
import * as $$$$$$25 from "./sections/Content/Tip.tsx";
import * as $$$$$$26 from "./sections/Content/Tutorial.tsx";
import * as $$$$$$27 from "./sections/Content/TutorialWithInformation.tsx";
import * as $$$$$$28 from "./sections/Content/VideoModal.tsx";
import * as $$$$$$29 from "./sections/Footer/Footer.tsx";
import * as $$$$$$30 from "./sections/Header/Header.tsx";
import * as $$$$$$31 from "./sections/Images/BannerGrid.tsx";
import * as $$$$$$32 from "./sections/Images/BannerTextButton.tsx";
import * as $$$$$$33 from "./sections/Images/Carousel.tsx";
import * as $$$$$$34 from "./sections/Images/ImageGallery.tsx";
import * as $$$$$$35 from "./sections/Images/InformativeBanner.tsx";
import * as $$$$$$36 from "./sections/Images/ShoppableBanner.tsx";
import * as $$$$$$37 from "./sections/Links/LinkTree.tsx";
import * as $$$$$$38 from "./sections/Links/Shortcuts.tsx";
import * as $$$$$$39 from "./sections/Miscellaneous/CookieConsent.tsx";
import * as $$$$$$40 from "./sections/Newsletter/Newsletter.tsx";
import * as $$$$$$41 from "./sections/Product/Details/ProductDetailsAdditionalInfo.tsx";
import * as $$$$$$42 from "./sections/Product/Details/ProductReviews.tsx";
import * as $$$$$$43 from "./sections/Product/ProductBannerShelf.tsx";
import * as $$$$$$44 from "./sections/Product/ProductBestDailyOffers.tsx";
import * as $$$$$$45 from "./sections/Product/ProductDetails.tsx";
import * as $$$$$$46 from "./sections/Product/ProductShelf.tsx";
import * as $$$$$$47 from "./sections/Product/ProductShelfAndImage.tsx";
import * as $$$$$$48 from "./sections/Product/SearchResult.tsx";
import * as $$$$$$49 from "./sections/Product/SingleProductShelf.tsx";
import * as $$$$$$50 from "./sections/Product/VisitedProductShelf.tsx";
import * as $$$$$$51 from "./sections/Social/InstagramPosts.tsx";
import * as $$$$$$52 from "./sections/Social/WhatsApp.tsx";
import * as $$$$$$53 from "./sections/Theme/Theme.tsx";

const manifest = {
  "loaders": {
    "deco-sites/otica-isabela/loaders/actions/cart/addItem.ts": $$$0,
    "deco-sites/otica-isabela/loaders/actions/wishlist/addItem.ts": $$$1,
    "deco-sites/otica-isabela/loaders/actions/wishlist/removeItem.ts": $$$2,
    "deco-sites/otica-isabela/loaders/product/cart.ts": $$$3,
    "deco-sites/otica-isabela/loaders/product/productDetails.ts": $$$4,
    "deco-sites/otica-isabela/loaders/product/productList.ts": $$$5,
    "deco-sites/otica-isabela/loaders/product/productListiningPage.ts": $$$6,
    "deco-sites/otica-isabela/loaders/product/suggestions.ts": $$$7,
    "deco-sites/otica-isabela/loaders/product/testimonials.ts": $$$8,
    "deco-sites/otica-isabela/loaders/product/wishlist.ts": $$$9,
    "deco-sites/otica-isabela/loaders/store/auth.ts": $$$10,
    "deco-sites/otica-isabela/loaders/store/newsletter.ts": $$$11,
    "deco-sites/otica-isabela/loaders/store/session.ts": $$$12,
  },
  "sections": {
    "deco-sites/otica-isabela/sections/Category/CategoryBanner.tsx": $$$$$$0,
    "deco-sites/otica-isabela/sections/Category/CategoryText.tsx": $$$$$$1,
    "deco-sites/otica-isabela/sections/Content/About.tsx": $$$$$$2,
    "deco-sites/otica-isabela/sections/Content/AccordionGroup.tsx": $$$$$$3,
    "deco-sites/otica-isabela/sections/Content/AntiBenefits.tsx": $$$$$$4,
    "deco-sites/otica-isabela/sections/Content/AntiOptions.tsx": $$$$$$5,
    "deco-sites/otica-isabela/sections/Content/BenefitList.tsx": $$$$$$6,
    "deco-sites/otica-isabela/sections/Content/Benefits.tsx": $$$$$$7,
    "deco-sites/otica-isabela/sections/Content/Cards.tsx": $$$$$$8,
    "deco-sites/otica-isabela/sections/Content/CardsWithImage.tsx": $$$$$$9,
    "deco-sites/otica-isabela/sections/Content/ContactForm.tsx": $$$$$$10,
    "deco-sites/otica-isabela/sections/Content/ContactUs.tsx": $$$$$$11,
    "deco-sites/otica-isabela/sections/Content/CouponList.tsx": $$$$$$12,
    "deco-sites/otica-isabela/sections/Content/DeferredIframe.tsx": $$$$$$13,
    "deco-sites/otica-isabela/sections/Content/Faq.tsx": $$$$$$14,
    "deco-sites/otica-isabela/sections/Content/Hero.tsx": $$$$$$15,
    "deco-sites/otica-isabela/sections/Content/Image.tsx": $$$$$$16,
    "deco-sites/otica-isabela/sections/Content/InformationList.tsx": $$$$$$17,
    "deco-sites/otica-isabela/sections/Content/Institutional.tsx": $$$$$$18,
    "deco-sites/otica-isabela/sections/Content/Logos.tsx": $$$$$$19,
    "deco-sites/otica-isabela/sections/Content/Presentation.tsx": $$$$$$20,
    "deco-sites/otica-isabela/sections/Content/RichText.tsx": $$$$$$21,
    "deco-sites/otica-isabela/sections/Content/SimpleCard.tsx": $$$$$$22,
    "deco-sites/otica-isabela/sections/Content/Spacing.tsx": $$$$$$23,
    "deco-sites/otica-isabela/sections/Content/Testimonials.tsx": $$$$$$24,
    "deco-sites/otica-isabela/sections/Content/Tip.tsx": $$$$$$25,
    "deco-sites/otica-isabela/sections/Content/Tutorial.tsx": $$$$$$26,
    "deco-sites/otica-isabela/sections/Content/TutorialWithInformation.tsx":
      $$$$$$27,
    "deco-sites/otica-isabela/sections/Content/VideoModal.tsx": $$$$$$28,
    "deco-sites/otica-isabela/sections/Footer/Footer.tsx": $$$$$$29,
    "deco-sites/otica-isabela/sections/Header/Header.tsx": $$$$$$30,
    "deco-sites/otica-isabela/sections/Images/BannerGrid.tsx": $$$$$$31,
    "deco-sites/otica-isabela/sections/Images/BannerTextButton.tsx": $$$$$$32,
    "deco-sites/otica-isabela/sections/Images/Carousel.tsx": $$$$$$33,
    "deco-sites/otica-isabela/sections/Images/ImageGallery.tsx": $$$$$$34,
    "deco-sites/otica-isabela/sections/Images/InformativeBanner.tsx": $$$$$$35,
    "deco-sites/otica-isabela/sections/Images/ShoppableBanner.tsx": $$$$$$36,
    "deco-sites/otica-isabela/sections/Links/LinkTree.tsx": $$$$$$37,
    "deco-sites/otica-isabela/sections/Links/Shortcuts.tsx": $$$$$$38,
    "deco-sites/otica-isabela/sections/Miscellaneous/CookieConsent.tsx":
      $$$$$$39,
    "deco-sites/otica-isabela/sections/Newsletter/Newsletter.tsx": $$$$$$40,
    "deco-sites/otica-isabela/sections/Product/Details/ProductDetailsAdditionalInfo.tsx":
      $$$$$$41,
    "deco-sites/otica-isabela/sections/Product/Details/ProductReviews.tsx":
      $$$$$$42,
    "deco-sites/otica-isabela/sections/Product/ProductBannerShelf.tsx":
      $$$$$$43,
    "deco-sites/otica-isabela/sections/Product/ProductBestDailyOffers.tsx":
      $$$$$$44,
    "deco-sites/otica-isabela/sections/Product/ProductDetails.tsx": $$$$$$45,
    "deco-sites/otica-isabela/sections/Product/ProductShelf.tsx": $$$$$$46,
    "deco-sites/otica-isabela/sections/Product/ProductShelfAndImage.tsx":
      $$$$$$47,
    "deco-sites/otica-isabela/sections/Product/SearchResult.tsx": $$$$$$48,
    "deco-sites/otica-isabela/sections/Product/SingleProductShelf.tsx":
      $$$$$$49,
    "deco-sites/otica-isabela/sections/Product/VisitedProductShelf.tsx":
      $$$$$$50,
    "deco-sites/otica-isabela/sections/Social/InstagramPosts.tsx": $$$$$$51,
    "deco-sites/otica-isabela/sections/Social/WhatsApp.tsx": $$$$$$52,
    "deco-sites/otica-isabela/sections/Theme/Theme.tsx": $$$$$$53,
  },
  "apps": {
    "deco-sites/otica-isabela/apps/decohub.ts": $$$$$$$$$$$0,
    "deco-sites/otica-isabela/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "deco-sites/otica-isabela",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
